# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-09 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='site_uid',
            field=models.CharField(max_length=100),
        ),
    ]
