# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 08:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.CharField(max_length=100)),
                ('is_spam', models.BooleanField(default=False)),
                ('is_publised', models.NullBooleanField(default=True)),
            ],
            options={
                'abstract': False,
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('body', models.TextField(verbose_name='内容')),
                ('published_time', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='上次修改时间')),
                ('topic', models.CharField(blank=True, max_length=20, null=True, verbose_name='话题')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('ups', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('is_page', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('comments_allow', models.BooleanField(default=True)),
                ('attachment', models.FileField(upload_to='attachments', verbose_name='附件')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发起者')),
                ('collected_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected_user', related_query_name='collected_by', to=settings.AUTH_USER_MODEL, verbose_name='收藏的用户')),
                ('praised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='praised_user', related_query_name='praised_user', to=settings.AUTH_USER_MODEL, verbose_name='赞过的用户')),
            ],
            options={
                'verbose_name_plural': 'Post XX',
                'ordering': ['-published_time'],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.CharField(max_length=100)),
                ('reaction_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=200)),
                ('profile_image', models.URLField(blank=True, null=True)),
                ('comment_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Post')),
            ],
            options={
                'abstract': False,
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
