# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-01 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='mugshot',
            field=models.ImageField(blank=True, upload_to='upload/mugshots', verbose_name='头像'),
        ),
    ]
