# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-17 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('likes_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LikesDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('likes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='likes.Likes')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
