# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 02:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('likes', '0002_auto_20160617_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('trigger_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_objects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='likes',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='likesdetail',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='likesdetail',
            name='user',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
        migrations.DeleteModel(
            name='LikesDetail',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set([('trigger_user', 'content_type', 'object_id')]),
        ),
    ]
