# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usera', '0002_remove_forumuser_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumuser',
            name='fans',
        ),
        migrations.RemoveField(
            model_name='forumuser',
            name='focus_users',
        ),
        migrations.RemoveField(
            model_name='forumuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='forumuser',
            name='github',
        ),
        migrations.RemoveField(
            model_name='forumuser',
            name='last_login_ip',
        ),
        migrations.RemoveField(
            model_name='forumuser',
            name='last_login_time',
        ),
        migrations.RemoveField(
            model_name='forumuser',
            name='mugshot',
        ),
        migrations.RemoveField(
            model_name='forumuser',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='forumuser',
            name='position',
        ),
        migrations.RemoveField(
            model_name='forumuser',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='forumuser',
            name='self_intro',
        ),
        migrations.RemoveField(
            model_name='forumuser',
            name='sign_up_ip',
        ),
        migrations.RemoveField(
            model_name='forumuser',
            name='website',
        ),
    ]
